const { exec } = require("child_process");
const path = require("path");
const fs = require("fs");

function transcribeAudio(audioPath) {
  return new Promise((resolve, reject) => {

    const outputDir = path.resolve("./temp");

    console.log("---- Speech To Text Started ----");
    console.log("Audio Path:", audioPath);
    console.log("Audio Exists:", fs.existsSync(audioPath));

    if (!fs.existsSync(audioPath)) {
      return reject("Audio file does not exist");
    }

    // ✅ Direct Python 3.11 path (fixed version)
    const command = `"C:\\Users\\Sweth\\AppData\\Local\\Programs\\Python\\Python311\\python.exe" -m whisper "${audioPath}" --model base --output_dir "${outputDir}" --output_format txt`;

    console.log("Running Command:", command);

    exec(command, (error, stdout, stderr) => {

      console.log("Whisper STDOUT:\n", stdout);
      console.log("Whisper STDERR:\n", stderr);

      if (error) {
        console.error("Whisper Execution Error:", error);
        return reject(stderr || error.message);
      }

      try {
        // 🔍 Find latest .txt file inside temp folder
        const files = fs.readdirSync(outputDir)
          .filter(file => file.endsWith(".txt"))
          .map(file => ({
            name: file,
            time: fs.statSync(path.join(outputDir, file)).mtime.getTime()
          }))
          .sort((a, b) => b.time - a.time);

        if (files.length === 0) {
          return reject("No transcript file generated by Whisper");
        }

        const latestFilePath = path.join(outputDir, files[0].name);

        console.log("Transcript File Found:", latestFilePath);

        const transcript = fs.readFileSync(latestFilePath, "utf8");

        console.log("---- Speech To Text Completed ----");

        resolve(transcript);

      } catch (err) {
        console.error("File Reading Error:", err);
        reject("Transcript file not found after whisper execution");
      }
    });

  });
}

module.exports = transcribeAudio;